### ISSUE TITLE
index.js and index.d.ts in wrong path after build

### ISSUE THREAD

**Issue by yangtfu** [lucasvtiradentes/ticktick-api-lvt#12]
![image](https://github.com/lucasvtiradentes/ticktick-api-lvt/assets/14918820/ba88d1b5-1116-4d94-af62-a2a6526b14be)
As shown in the pic, which results in 'ERR_MODULE_NOT_FOUND' error

**Comment by lucasvtiradentes** [comment]
@yangtfu, thanks for pointing that out! I have just fixed it, but as specified on [this issue](https://github.com/lucasvtiradentes/ticktick-api-lvt/issues/13), ticktick have made some changes recently and I have not succeed  yet on be able to login it again.
